# Enumeration for the state of the conveyor

IDLE = 0
HOMING = 1
MOVING_TO_POSITION_HOME = 2
MOVING_TO_POSITION_1 = 3
MOVING_TO_POSITION_2 = 4
SET_POSITION_GENERAL = 5
SET_POSITION_1 = 6
SET_POSITION_2 = 7
